# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lunarix/Projects/mini_lang

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lunarix/Projects/mini_lang

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lunarix/Projects/mini_lang/CMakeFiles /home/lunarix/Projects/mini_lang//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lunarix/Projects/mini_lang/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cclonk

# Build rule for target.
cclonk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cclonk
.PHONY : cclonk

# fast build rule for target.
cclonk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/build
.PHONY : cclonk/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

src/libclonk/lexer/debug.o: src/libclonk/lexer/debug.c.o
.PHONY : src/libclonk/lexer/debug.o

# target to build an object file
src/libclonk/lexer/debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/lexer/debug.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/lexer/debug.c.o
.PHONY : src/libclonk/lexer/debug.c.o

src/libclonk/lexer/debug.i: src/libclonk/lexer/debug.c.i
.PHONY : src/libclonk/lexer/debug.i

# target to preprocess a source file
src/libclonk/lexer/debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/lexer/debug.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/lexer/debug.c.i
.PHONY : src/libclonk/lexer/debug.c.i

src/libclonk/lexer/debug.s: src/libclonk/lexer/debug.c.s
.PHONY : src/libclonk/lexer/debug.s

# target to generate assembly for a file
src/libclonk/lexer/debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/lexer/debug.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/lexer/debug.c.s
.PHONY : src/libclonk/lexer/debug.c.s

src/libclonk/lexer/helpers.o: src/libclonk/lexer/helpers.c.o
.PHONY : src/libclonk/lexer/helpers.o

# target to build an object file
src/libclonk/lexer/helpers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/lexer/helpers.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/lexer/helpers.c.o
.PHONY : src/libclonk/lexer/helpers.c.o

src/libclonk/lexer/helpers.i: src/libclonk/lexer/helpers.c.i
.PHONY : src/libclonk/lexer/helpers.i

# target to preprocess a source file
src/libclonk/lexer/helpers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/lexer/helpers.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/lexer/helpers.c.i
.PHONY : src/libclonk/lexer/helpers.c.i

src/libclonk/lexer/helpers.s: src/libclonk/lexer/helpers.c.s
.PHONY : src/libclonk/lexer/helpers.s

# target to generate assembly for a file
src/libclonk/lexer/helpers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/lexer/helpers.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/lexer/helpers.c.s
.PHONY : src/libclonk/lexer/helpers.c.s

src/libclonk/lexer/lexer.o: src/libclonk/lexer/lexer.c.o
.PHONY : src/libclonk/lexer/lexer.o

# target to build an object file
src/libclonk/lexer/lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/lexer/lexer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/lexer/lexer.c.o
.PHONY : src/libclonk/lexer/lexer.c.o

src/libclonk/lexer/lexer.i: src/libclonk/lexer/lexer.c.i
.PHONY : src/libclonk/lexer/lexer.i

# target to preprocess a source file
src/libclonk/lexer/lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/lexer/lexer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/lexer/lexer.c.i
.PHONY : src/libclonk/lexer/lexer.c.i

src/libclonk/lexer/lexer.s: src/libclonk/lexer/lexer.c.s
.PHONY : src/libclonk/lexer/lexer.s

# target to generate assembly for a file
src/libclonk/lexer/lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/lexer/lexer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/lexer/lexer.c.s
.PHONY : src/libclonk/lexer/lexer.c.s

src/libclonk/parser/error.o: src/libclonk/parser/error.c.o
.PHONY : src/libclonk/parser/error.o

# target to build an object file
src/libclonk/parser/error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/error.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/error.c.o
.PHONY : src/libclonk/parser/error.c.o

src/libclonk/parser/error.i: src/libclonk/parser/error.c.i
.PHONY : src/libclonk/parser/error.i

# target to preprocess a source file
src/libclonk/parser/error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/error.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/error.c.i
.PHONY : src/libclonk/parser/error.c.i

src/libclonk/parser/error.s: src/libclonk/parser/error.c.s
.PHONY : src/libclonk/parser/error.s

# target to generate assembly for a file
src/libclonk/parser/error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/error.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/error.c.s
.PHONY : src/libclonk/parser/error.c.s

src/libclonk/parser/parser.o: src/libclonk/parser/parser.c.o
.PHONY : src/libclonk/parser/parser.o

# target to build an object file
src/libclonk/parser/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/parser.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/parser.c.o
.PHONY : src/libclonk/parser/parser.c.o

src/libclonk/parser/parser.i: src/libclonk/parser/parser.c.i
.PHONY : src/libclonk/parser/parser.i

# target to preprocess a source file
src/libclonk/parser/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/parser.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/parser.c.i
.PHONY : src/libclonk/parser/parser.c.i

src/libclonk/parser/parser.s: src/libclonk/parser/parser.c.s
.PHONY : src/libclonk/parser/parser.s

# target to generate assembly for a file
src/libclonk/parser/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/parser.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/parser.c.s
.PHONY : src/libclonk/parser/parser.c.s

src/libclonk/parser/semantic_utils.o: src/libclonk/parser/semantic_utils.c.o
.PHONY : src/libclonk/parser/semantic_utils.o

# target to build an object file
src/libclonk/parser/semantic_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/semantic_utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/semantic_utils.c.o
.PHONY : src/libclonk/parser/semantic_utils.c.o

src/libclonk/parser/semantic_utils.i: src/libclonk/parser/semantic_utils.c.i
.PHONY : src/libclonk/parser/semantic_utils.i

# target to preprocess a source file
src/libclonk/parser/semantic_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/semantic_utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/semantic_utils.c.i
.PHONY : src/libclonk/parser/semantic_utils.c.i

src/libclonk/parser/semantic_utils.s: src/libclonk/parser/semantic_utils.c.s
.PHONY : src/libclonk/parser/semantic_utils.s

# target to generate assembly for a file
src/libclonk/parser/semantic_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/semantic_utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/semantic_utils.c.s
.PHONY : src/libclonk/parser/semantic_utils.c.s

src/libclonk/parser/semantics.o: src/libclonk/parser/semantics.c.o
.PHONY : src/libclonk/parser/semantics.o

# target to build an object file
src/libclonk/parser/semantics.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/semantics.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/semantics.c.o
.PHONY : src/libclonk/parser/semantics.c.o

src/libclonk/parser/semantics.i: src/libclonk/parser/semantics.c.i
.PHONY : src/libclonk/parser/semantics.i

# target to preprocess a source file
src/libclonk/parser/semantics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/semantics.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/semantics.c.i
.PHONY : src/libclonk/parser/semantics.c.i

src/libclonk/parser/semantics.s: src/libclonk/parser/semantics.c.s
.PHONY : src/libclonk/parser/semantics.s

# target to generate assembly for a file
src/libclonk/parser/semantics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/semantics.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/semantics.c.s
.PHONY : src/libclonk/parser/semantics.c.s

src/libclonk/parser/utils.o: src/libclonk/parser/utils.c.o
.PHONY : src/libclonk/parser/utils.o

# target to build an object file
src/libclonk/parser/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/utils.c.o
.PHONY : src/libclonk/parser/utils.c.o

src/libclonk/parser/utils.i: src/libclonk/parser/utils.c.i
.PHONY : src/libclonk/parser/utils.i

# target to preprocess a source file
src/libclonk/parser/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/utils.c.i
.PHONY : src/libclonk/parser/utils.c.i

src/libclonk/parser/utils.s: src/libclonk/parser/utils.c.s
.PHONY : src/libclonk/parser/utils.s

# target to generate assembly for a file
src/libclonk/parser/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libclonk/parser/utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libclonk/parser/utils.c.s
.PHONY : src/libclonk/parser/utils.c.s

src/libstdonk/int.o: src/libstdonk/int.c.o
.PHONY : src/libstdonk/int.o

# target to build an object file
src/libstdonk/int.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libstdonk/int.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libstdonk/int.c.o
.PHONY : src/libstdonk/int.c.o

src/libstdonk/int.i: src/libstdonk/int.c.i
.PHONY : src/libstdonk/int.i

# target to preprocess a source file
src/libstdonk/int.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libstdonk/int.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libstdonk/int.c.i
.PHONY : src/libstdonk/int.c.i

src/libstdonk/int.s: src/libstdonk/int.c.s
.PHONY : src/libstdonk/int.s

# target to generate assembly for a file
src/libstdonk/int.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libstdonk/int.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libstdonk/int.c.s
.PHONY : src/libstdonk/int.c.s

src/libstdonk/queue.o: src/libstdonk/queue.c.o
.PHONY : src/libstdonk/queue.o

# target to build an object file
src/libstdonk/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libstdonk/queue.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libstdonk/queue.c.o
.PHONY : src/libstdonk/queue.c.o

src/libstdonk/queue.i: src/libstdonk/queue.c.i
.PHONY : src/libstdonk/queue.i

# target to preprocess a source file
src/libstdonk/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libstdonk/queue.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libstdonk/queue.c.i
.PHONY : src/libstdonk/queue.c.i

src/libstdonk/queue.s: src/libstdonk/queue.c.s
.PHONY : src/libstdonk/queue.s

# target to generate assembly for a file
src/libstdonk/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libstdonk/queue.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libstdonk/queue.c.s
.PHONY : src/libstdonk/queue.c.s

src/libstdonk/sort_merge.o: src/libstdonk/sort_merge.c.o
.PHONY : src/libstdonk/sort_merge.o

# target to build an object file
src/libstdonk/sort_merge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libstdonk/sort_merge.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libstdonk/sort_merge.c.o
.PHONY : src/libstdonk/sort_merge.c.o

src/libstdonk/sort_merge.i: src/libstdonk/sort_merge.c.i
.PHONY : src/libstdonk/sort_merge.i

# target to preprocess a source file
src/libstdonk/sort_merge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libstdonk/sort_merge.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libstdonk/sort_merge.c.i
.PHONY : src/libstdonk/sort_merge.c.i

src/libstdonk/sort_merge.s: src/libstdonk/sort_merge.c.s
.PHONY : src/libstdonk/sort_merge.s

# target to generate assembly for a file
src/libstdonk/sort_merge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libstdonk/sort_merge.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libstdonk/sort_merge.c.s
.PHONY : src/libstdonk/sort_merge.c.s

src/libstdonk/vec.o: src/libstdonk/vec.c.o
.PHONY : src/libstdonk/vec.o

# target to build an object file
src/libstdonk/vec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libstdonk/vec.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libstdonk/vec.c.o
.PHONY : src/libstdonk/vec.c.o

src/libstdonk/vec.i: src/libstdonk/vec.c.i
.PHONY : src/libstdonk/vec.i

# target to preprocess a source file
src/libstdonk/vec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libstdonk/vec.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libstdonk/vec.c.i
.PHONY : src/libstdonk/vec.c.i

src/libstdonk/vec.s: src/libstdonk/vec.c.s
.PHONY : src/libstdonk/vec.s

# target to generate assembly for a file
src/libstdonk/vec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/libstdonk/vec.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libstdonk/vec.c.s
.PHONY : src/libstdonk/vec.c.s

src/libtest/CuTest/CuStr.o: src/libtest/CuTest/CuStr.c.o
.PHONY : src/libtest/CuTest/CuStr.o

# target to build an object file
src/libtest/CuTest/CuStr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/CuTest/CuStr.c.o
.PHONY : src/libtest/CuTest/CuStr.c.o

src/libtest/CuTest/CuStr.i: src/libtest/CuTest/CuStr.c.i
.PHONY : src/libtest/CuTest/CuStr.i

# target to preprocess a source file
src/libtest/CuTest/CuStr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/CuTest/CuStr.c.i
.PHONY : src/libtest/CuTest/CuStr.c.i

src/libtest/CuTest/CuStr.s: src/libtest/CuTest/CuStr.c.s
.PHONY : src/libtest/CuTest/CuStr.s

# target to generate assembly for a file
src/libtest/CuTest/CuStr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/CuTest/CuStr.c.s
.PHONY : src/libtest/CuTest/CuStr.c.s

src/libtest/CuTest/CuTest.o: src/libtest/CuTest/CuTest.c.o
.PHONY : src/libtest/CuTest/CuTest.o

# target to build an object file
src/libtest/CuTest/CuTest.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/CuTest/CuTest.c.o
.PHONY : src/libtest/CuTest/CuTest.c.o

src/libtest/CuTest/CuTest.i: src/libtest/CuTest/CuTest.c.i
.PHONY : src/libtest/CuTest/CuTest.i

# target to preprocess a source file
src/libtest/CuTest/CuTest.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/CuTest/CuTest.c.i
.PHONY : src/libtest/CuTest/CuTest.c.i

src/libtest/CuTest/CuTest.s: src/libtest/CuTest/CuTest.c.s
.PHONY : src/libtest/CuTest/CuTest.s

# target to generate assembly for a file
src/libtest/CuTest/CuTest.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/CuTest/CuTest.c.s
.PHONY : src/libtest/CuTest/CuTest.c.s

src/libtest/CuTest/suite.o: src/libtest/CuTest/suite.c.o
.PHONY : src/libtest/CuTest/suite.o

# target to build an object file
src/libtest/CuTest/suite.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/CuTest/suite.c.o
.PHONY : src/libtest/CuTest/suite.c.o

src/libtest/CuTest/suite.i: src/libtest/CuTest/suite.c.i
.PHONY : src/libtest/CuTest/suite.i

# target to preprocess a source file
src/libtest/CuTest/suite.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/CuTest/suite.c.i
.PHONY : src/libtest/CuTest/suite.c.i

src/libtest/CuTest/suite.s: src/libtest/CuTest/suite.c.s
.PHONY : src/libtest/CuTest/suite.s

# target to generate assembly for a file
src/libtest/CuTest/suite.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/CuTest/suite.c.s
.PHONY : src/libtest/CuTest/suite.c.s

src/libtest/build_mask.o: src/libtest/build_mask.c.o
.PHONY : src/libtest/build_mask.o

# target to build an object file
src/libtest/build_mask.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/build_mask.c.o
.PHONY : src/libtest/build_mask.c.o

src/libtest/build_mask.i: src/libtest/build_mask.c.i
.PHONY : src/libtest/build_mask.i

# target to preprocess a source file
src/libtest/build_mask.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/build_mask.c.i
.PHONY : src/libtest/build_mask.c.i

src/libtest/build_mask.s: src/libtest/build_mask.c.s
.PHONY : src/libtest/build_mask.s

# target to generate assembly for a file
src/libtest/build_mask.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/build_mask.c.s
.PHONY : src/libtest/build_mask.c.s

src/libtest/mask_assert.o: src/libtest/mask_assert.c.o
.PHONY : src/libtest/mask_assert.o

# target to build an object file
src/libtest/mask_assert.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/mask_assert.c.o
.PHONY : src/libtest/mask_assert.c.o

src/libtest/mask_assert.i: src/libtest/mask_assert.c.i
.PHONY : src/libtest/mask_assert.i

# target to preprocess a source file
src/libtest/mask_assert.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/mask_assert.c.i
.PHONY : src/libtest/mask_assert.c.i

src/libtest/mask_assert.s: src/libtest/mask_assert.c.s
.PHONY : src/libtest/mask_assert.s

# target to generate assembly for a file
src/libtest/mask_assert.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/mask_assert.c.s
.PHONY : src/libtest/mask_assert.c.s

src/libtest/textutil.o: src/libtest/textutil.c.o
.PHONY : src/libtest/textutil.o

# target to build an object file
src/libtest/textutil.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/textutil.c.o
.PHONY : src/libtest/textutil.c.o

src/libtest/textutil.i: src/libtest/textutil.c.i
.PHONY : src/libtest/textutil.i

# target to preprocess a source file
src/libtest/textutil.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/textutil.c.i
.PHONY : src/libtest/textutil.c.i

src/libtest/textutil.s: src/libtest/textutil.c.s
.PHONY : src/libtest/textutil.s

# target to generate assembly for a file
src/libtest/textutil.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/textutil.c.s
.PHONY : src/libtest/textutil.c.s

src/libtest/tokens.o: src/libtest/tokens.c.o
.PHONY : src/libtest/tokens.o

# target to build an object file
src/libtest/tokens.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/tokens.c.o
.PHONY : src/libtest/tokens.c.o

src/libtest/tokens.i: src/libtest/tokens.c.i
.PHONY : src/libtest/tokens.i

# target to preprocess a source file
src/libtest/tokens.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/tokens.c.i
.PHONY : src/libtest/tokens.c.i

src/libtest/tokens.s: src/libtest/tokens.c.s
.PHONY : src/libtest/tokens.s

# target to generate assembly for a file
src/libtest/tokens.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/libtest/tokens.c.s
.PHONY : src/libtest/tokens.c.s

src/repl.o: src/repl.c.o
.PHONY : src/repl.o

# target to build an object file
src/repl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/repl.c.o
.PHONY : src/repl.c.o

src/repl.i: src/repl.c.i
.PHONY : src/repl.i

# target to preprocess a source file
src/repl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/repl.c.i
.PHONY : src/repl.c.i

src/repl.s: src/repl.c.s
.PHONY : src/repl.s

# target to generate assembly for a file
src/repl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cclonk.dir/build.make CMakeFiles/cclonk.dir/src/repl.c.s
.PHONY : src/repl.c.s

src/tests/libclonk/lexer/harness.o: src/tests/libclonk/lexer/harness.c.o
.PHONY : src/tests/libclonk/lexer/harness.o

# target to build an object file
src/tests/libclonk/lexer/harness.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/lexer/harness.c.o
.PHONY : src/tests/libclonk/lexer/harness.c.o

src/tests/libclonk/lexer/harness.i: src/tests/libclonk/lexer/harness.c.i
.PHONY : src/tests/libclonk/lexer/harness.i

# target to preprocess a source file
src/tests/libclonk/lexer/harness.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/lexer/harness.c.i
.PHONY : src/tests/libclonk/lexer/harness.c.i

src/tests/libclonk/lexer/harness.s: src/tests/libclonk/lexer/harness.c.s
.PHONY : src/tests/libclonk/lexer/harness.s

# target to generate assembly for a file
src/tests/libclonk/lexer/harness.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/lexer/harness.c.s
.PHONY : src/tests/libclonk/lexer/harness.c.s

src/tests/libclonk/lexer/lexer_tests.o: src/tests/libclonk/lexer/lexer_tests.c.o
.PHONY : src/tests/libclonk/lexer/lexer_tests.o

# target to build an object file
src/tests/libclonk/lexer/lexer_tests.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/lexer/lexer_tests.c.o
.PHONY : src/tests/libclonk/lexer/lexer_tests.c.o

src/tests/libclonk/lexer/lexer_tests.i: src/tests/libclonk/lexer/lexer_tests.c.i
.PHONY : src/tests/libclonk/lexer/lexer_tests.i

# target to preprocess a source file
src/tests/libclonk/lexer/lexer_tests.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/lexer/lexer_tests.c.i
.PHONY : src/tests/libclonk/lexer/lexer_tests.c.i

src/tests/libclonk/lexer/lexer_tests.s: src/tests/libclonk/lexer/lexer_tests.c.s
.PHONY : src/tests/libclonk/lexer/lexer_tests.s

# target to generate assembly for a file
src/tests/libclonk/lexer/lexer_tests.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/lexer/lexer_tests.c.s
.PHONY : src/tests/libclonk/lexer/lexer_tests.c.s

src/tests/libclonk/parser/parser.o: src/tests/libclonk/parser/parser.c.o
.PHONY : src/tests/libclonk/parser/parser.o

# target to build an object file
src/tests/libclonk/parser/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/parser/parser.c.o
.PHONY : src/tests/libclonk/parser/parser.c.o

src/tests/libclonk/parser/parser.i: src/tests/libclonk/parser/parser.c.i
.PHONY : src/tests/libclonk/parser/parser.i

# target to preprocess a source file
src/tests/libclonk/parser/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/parser/parser.c.i
.PHONY : src/tests/libclonk/parser/parser.c.i

src/tests/libclonk/parser/parser.s: src/tests/libclonk/parser/parser.c.s
.PHONY : src/tests/libclonk/parser/parser.s

# target to generate assembly for a file
src/tests/libclonk/parser/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/parser/parser.c.s
.PHONY : src/tests/libclonk/parser/parser.c.s

src/tests/libclonk/parser/predict.o: src/tests/libclonk/parser/predict.c.o
.PHONY : src/tests/libclonk/parser/predict.o

# target to build an object file
src/tests/libclonk/parser/predict.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/parser/predict.c.o
.PHONY : src/tests/libclonk/parser/predict.c.o

src/tests/libclonk/parser/predict.i: src/tests/libclonk/parser/predict.c.i
.PHONY : src/tests/libclonk/parser/predict.i

# target to preprocess a source file
src/tests/libclonk/parser/predict.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/parser/predict.c.i
.PHONY : src/tests/libclonk/parser/predict.c.i

src/tests/libclonk/parser/predict.s: src/tests/libclonk/parser/predict.c.s
.PHONY : src/tests/libclonk/parser/predict.s

# target to generate assembly for a file
src/tests/libclonk/parser/predict.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/parser/predict.c.s
.PHONY : src/tests/libclonk/parser/predict.c.s

src/tests/libclonk/parser/semantics.o: src/tests/libclonk/parser/semantics.c.o
.PHONY : src/tests/libclonk/parser/semantics.o

# target to build an object file
src/tests/libclonk/parser/semantics.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/parser/semantics.c.o
.PHONY : src/tests/libclonk/parser/semantics.c.o

src/tests/libclonk/parser/semantics.i: src/tests/libclonk/parser/semantics.c.i
.PHONY : src/tests/libclonk/parser/semantics.i

# target to preprocess a source file
src/tests/libclonk/parser/semantics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/parser/semantics.c.i
.PHONY : src/tests/libclonk/parser/semantics.c.i

src/tests/libclonk/parser/semantics.s: src/tests/libclonk/parser/semantics.c.s
.PHONY : src/tests/libclonk/parser/semantics.s

# target to generate assembly for a file
src/tests/libclonk/parser/semantics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libclonk/parser/semantics.c.s
.PHONY : src/tests/libclonk/parser/semantics.c.s

src/tests/libstdonk/merge_sort.o: src/tests/libstdonk/merge_sort.c.o
.PHONY : src/tests/libstdonk/merge_sort.o

# target to build an object file
src/tests/libstdonk/merge_sort.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libstdonk/merge_sort.c.o
.PHONY : src/tests/libstdonk/merge_sort.c.o

src/tests/libstdonk/merge_sort.i: src/tests/libstdonk/merge_sort.c.i
.PHONY : src/tests/libstdonk/merge_sort.i

# target to preprocess a source file
src/tests/libstdonk/merge_sort.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libstdonk/merge_sort.c.i
.PHONY : src/tests/libstdonk/merge_sort.c.i

src/tests/libstdonk/merge_sort.s: src/tests/libstdonk/merge_sort.c.s
.PHONY : src/tests/libstdonk/merge_sort.s

# target to generate assembly for a file
src/tests/libstdonk/merge_sort.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libstdonk/merge_sort.c.s
.PHONY : src/tests/libstdonk/merge_sort.c.s

src/tests/libstdonk/queue.o: src/tests/libstdonk/queue.c.o
.PHONY : src/tests/libstdonk/queue.o

# target to build an object file
src/tests/libstdonk/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libstdonk/queue.c.o
.PHONY : src/tests/libstdonk/queue.c.o

src/tests/libstdonk/queue.i: src/tests/libstdonk/queue.c.i
.PHONY : src/tests/libstdonk/queue.i

# target to preprocess a source file
src/tests/libstdonk/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libstdonk/queue.c.i
.PHONY : src/tests/libstdonk/queue.c.i

src/tests/libstdonk/queue.s: src/tests/libstdonk/queue.c.s
.PHONY : src/tests/libstdonk/queue.s

# target to generate assembly for a file
src/tests/libstdonk/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libstdonk/queue.c.s
.PHONY : src/tests/libstdonk/queue.c.s

src/tests/libstdonk/vec.o: src/tests/libstdonk/vec.c.o
.PHONY : src/tests/libstdonk/vec.o

# target to build an object file
src/tests/libstdonk/vec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libstdonk/vec.c.o
.PHONY : src/tests/libstdonk/vec.c.o

src/tests/libstdonk/vec.i: src/tests/libstdonk/vec.c.i
.PHONY : src/tests/libstdonk/vec.i

# target to preprocess a source file
src/tests/libstdonk/vec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libstdonk/vec.c.i
.PHONY : src/tests/libstdonk/vec.c.i

src/tests/libstdonk/vec.s: src/tests/libstdonk/vec.c.s
.PHONY : src/tests/libstdonk/vec.s

# target to generate assembly for a file
src/tests/libstdonk/vec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libstdonk/vec.c.s
.PHONY : src/tests/libstdonk/vec.c.s

src/tests/libtest/CuTestTest.o: src/tests/libtest/CuTestTest.c.o
.PHONY : src/tests/libtest/CuTestTest.o

# target to build an object file
src/tests/libtest/CuTestTest.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libtest/CuTestTest.c.o
.PHONY : src/tests/libtest/CuTestTest.c.o

src/tests/libtest/CuTestTest.i: src/tests/libtest/CuTestTest.c.i
.PHONY : src/tests/libtest/CuTestTest.i

# target to preprocess a source file
src/tests/libtest/CuTestTest.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libtest/CuTestTest.c.i
.PHONY : src/tests/libtest/CuTestTest.c.i

src/tests/libtest/CuTestTest.s: src/tests/libtest/CuTestTest.c.s
.PHONY : src/tests/libtest/CuTestTest.s

# target to generate assembly for a file
src/tests/libtest/CuTestTest.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libtest/CuTestTest.c.s
.PHONY : src/tests/libtest/CuTestTest.c.s

src/tests/libtest/test_assert.o: src/tests/libtest/test_assert.c.o
.PHONY : src/tests/libtest/test_assert.o

# target to build an object file
src/tests/libtest/test_assert.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libtest/test_assert.c.o
.PHONY : src/tests/libtest/test_assert.c.o

src/tests/libtest/test_assert.i: src/tests/libtest/test_assert.c.i
.PHONY : src/tests/libtest/test_assert.i

# target to preprocess a source file
src/tests/libtest/test_assert.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libtest/test_assert.c.i
.PHONY : src/tests/libtest/test_assert.c.i

src/tests/libtest/test_assert.s: src/tests/libtest/test_assert.c.s
.PHONY : src/tests/libtest/test_assert.s

# target to generate assembly for a file
src/tests/libtest/test_assert.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libtest/test_assert.c.s
.PHONY : src/tests/libtest/test_assert.c.s

src/tests/libtest/test_mask.o: src/tests/libtest/test_mask.c.o
.PHONY : src/tests/libtest/test_mask.o

# target to build an object file
src/tests/libtest/test_mask.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libtest/test_mask.c.o
.PHONY : src/tests/libtest/test_mask.c.o

src/tests/libtest/test_mask.i: src/tests/libtest/test_mask.c.i
.PHONY : src/tests/libtest/test_mask.i

# target to preprocess a source file
src/tests/libtest/test_mask.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libtest/test_mask.c.i
.PHONY : src/tests/libtest/test_mask.c.i

src/tests/libtest/test_mask.s: src/tests/libtest/test_mask.c.s
.PHONY : src/tests/libtest/test_mask.s

# target to generate assembly for a file
src/tests/libtest/test_mask.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/libtest/test_mask.c.s
.PHONY : src/tests/libtest/test_mask.c.s

src/tests/run_tests.o: src/tests/run_tests.c.o
.PHONY : src/tests/run_tests.o

# target to build an object file
src/tests/run_tests.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/run_tests.c.o
.PHONY : src/tests/run_tests.c.o

src/tests/run_tests.i: src/tests/run_tests.c.i
.PHONY : src/tests/run_tests.i

# target to preprocess a source file
src/tests/run_tests.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/run_tests.c.i
.PHONY : src/tests/run_tests.c.i

src/tests/run_tests.s: src/tests/run_tests.c.s
.PHONY : src/tests/run_tests.s

# target to generate assembly for a file
src/tests/run_tests.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/tests/run_tests.c.s
.PHONY : src/tests/run_tests.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cclonk"
	@echo "... test"
	@echo "... src/libclonk/lexer/debug.o"
	@echo "... src/libclonk/lexer/debug.i"
	@echo "... src/libclonk/lexer/debug.s"
	@echo "... src/libclonk/lexer/helpers.o"
	@echo "... src/libclonk/lexer/helpers.i"
	@echo "... src/libclonk/lexer/helpers.s"
	@echo "... src/libclonk/lexer/lexer.o"
	@echo "... src/libclonk/lexer/lexer.i"
	@echo "... src/libclonk/lexer/lexer.s"
	@echo "... src/libclonk/parser/error.o"
	@echo "... src/libclonk/parser/error.i"
	@echo "... src/libclonk/parser/error.s"
	@echo "... src/libclonk/parser/parser.o"
	@echo "... src/libclonk/parser/parser.i"
	@echo "... src/libclonk/parser/parser.s"
	@echo "... src/libclonk/parser/semantic_utils.o"
	@echo "... src/libclonk/parser/semantic_utils.i"
	@echo "... src/libclonk/parser/semantic_utils.s"
	@echo "... src/libclonk/parser/semantics.o"
	@echo "... src/libclonk/parser/semantics.i"
	@echo "... src/libclonk/parser/semantics.s"
	@echo "... src/libclonk/parser/utils.o"
	@echo "... src/libclonk/parser/utils.i"
	@echo "... src/libclonk/parser/utils.s"
	@echo "... src/libstdonk/int.o"
	@echo "... src/libstdonk/int.i"
	@echo "... src/libstdonk/int.s"
	@echo "... src/libstdonk/queue.o"
	@echo "... src/libstdonk/queue.i"
	@echo "... src/libstdonk/queue.s"
	@echo "... src/libstdonk/sort_merge.o"
	@echo "... src/libstdonk/sort_merge.i"
	@echo "... src/libstdonk/sort_merge.s"
	@echo "... src/libstdonk/vec.o"
	@echo "... src/libstdonk/vec.i"
	@echo "... src/libstdonk/vec.s"
	@echo "... src/libtest/CuTest/CuStr.o"
	@echo "... src/libtest/CuTest/CuStr.i"
	@echo "... src/libtest/CuTest/CuStr.s"
	@echo "... src/libtest/CuTest/CuTest.o"
	@echo "... src/libtest/CuTest/CuTest.i"
	@echo "... src/libtest/CuTest/CuTest.s"
	@echo "... src/libtest/CuTest/suite.o"
	@echo "... src/libtest/CuTest/suite.i"
	@echo "... src/libtest/CuTest/suite.s"
	@echo "... src/libtest/build_mask.o"
	@echo "... src/libtest/build_mask.i"
	@echo "... src/libtest/build_mask.s"
	@echo "... src/libtest/mask_assert.o"
	@echo "... src/libtest/mask_assert.i"
	@echo "... src/libtest/mask_assert.s"
	@echo "... src/libtest/textutil.o"
	@echo "... src/libtest/textutil.i"
	@echo "... src/libtest/textutil.s"
	@echo "... src/libtest/tokens.o"
	@echo "... src/libtest/tokens.i"
	@echo "... src/libtest/tokens.s"
	@echo "... src/repl.o"
	@echo "... src/repl.i"
	@echo "... src/repl.s"
	@echo "... src/tests/libclonk/lexer/harness.o"
	@echo "... src/tests/libclonk/lexer/harness.i"
	@echo "... src/tests/libclonk/lexer/harness.s"
	@echo "... src/tests/libclonk/lexer/lexer_tests.o"
	@echo "... src/tests/libclonk/lexer/lexer_tests.i"
	@echo "... src/tests/libclonk/lexer/lexer_tests.s"
	@echo "... src/tests/libclonk/parser/parser.o"
	@echo "... src/tests/libclonk/parser/parser.i"
	@echo "... src/tests/libclonk/parser/parser.s"
	@echo "... src/tests/libclonk/parser/predict.o"
	@echo "... src/tests/libclonk/parser/predict.i"
	@echo "... src/tests/libclonk/parser/predict.s"
	@echo "... src/tests/libclonk/parser/semantics.o"
	@echo "... src/tests/libclonk/parser/semantics.i"
	@echo "... src/tests/libclonk/parser/semantics.s"
	@echo "... src/tests/libstdonk/merge_sort.o"
	@echo "... src/tests/libstdonk/merge_sort.i"
	@echo "... src/tests/libstdonk/merge_sort.s"
	@echo "... src/tests/libstdonk/queue.o"
	@echo "... src/tests/libstdonk/queue.i"
	@echo "... src/tests/libstdonk/queue.s"
	@echo "... src/tests/libstdonk/vec.o"
	@echo "... src/tests/libstdonk/vec.i"
	@echo "... src/tests/libstdonk/vec.s"
	@echo "... src/tests/libtest/CuTestTest.o"
	@echo "... src/tests/libtest/CuTestTest.i"
	@echo "... src/tests/libtest/CuTestTest.s"
	@echo "... src/tests/libtest/test_assert.o"
	@echo "... src/tests/libtest/test_assert.i"
	@echo "... src/tests/libtest/test_assert.s"
	@echo "... src/tests/libtest/test_mask.o"
	@echo "... src/tests/libtest/test_mask.i"
	@echo "... src/tests/libtest/test_mask.s"
	@echo "... src/tests/run_tests.o"
	@echo "... src/tests/run_tests.i"
	@echo "... src/tests/run_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

